//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit2Byte {


    public partial class Events {

        /// <summary>
        /// EventsStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal EventsStatus;

        /// <summary>
        /// EventsRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater EventsRepeater;
    }
}
