//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit2Byte
{
    public partial class Login
    {
        protected global::System.Web.UI.WebControls.ValidationSummary LoginValidationSummary;

        protected global::System.Web.UI.WebControls.Label StatusLabel;

        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;

        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;

        protected global::System.Web.UI.WebControls.Button LoginButton;
    }
}
