//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit2Byte
{
    public partial class Members
    {
        protected global::System.Web.UI.WebControls.Literal GreetingLiteral;
        protected global::System.Web.UI.WebControls.HyperLink ProfileLink;
        protected global::System.Web.UI.WebControls.Panel EmptyMembersPanel;
        protected global::System.Web.UI.WebControls.Repeater MembersRepeater;
    }
}
