//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit2Byte
{
    public partial class Register
    {
        protected global::System.Web.UI.WebControls.ValidationSummary RegisterValidationSummary;

        protected global::System.Web.UI.WebControls.Label StatusLabel;

        protected global::System.Web.UI.WebControls.TextBox FullNameTextBox;

        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;

        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;

        protected global::System.Web.UI.WebControls.RadioButtonList YearList;

        protected global::System.Web.UI.WebControls.CheckBoxList InterestList;

        protected global::System.Web.UI.WebControls.DropDownList RoleDropDown;

        protected global::System.Web.UI.WebControls.TextBox MessageTextBox;

        protected global::System.Web.UI.WebControls.Button SubmitRegistrationButton;
    }
}
