//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit2Byte.Admin {


    public partial class Events {

        /// <summary>
        /// StatusLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal StatusLiteral;

        /// <summary>
        /// NewTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox NewTitle;

        /// <summary>
        /// NewDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox NewDate;

        /// <summary>
        /// NewDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox NewDescription;

        /// <summary>
        /// AddEventButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button AddEventButton;

        /// <summary>
        /// EventsGrid control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView EventsGrid;
    }
}
