//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit2Byte.Admin {


    public partial class Users {

        /// <summary>
        /// StatusLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal StatusLiteral;

        /// <summary>
        /// UsersGrid control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView UsersGrid;
    }
}
