//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bit2Byte.MemberProfiles {


    public partial class Profile {

        /// <summary>
        /// StatusLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal StatusLiteral;

        /// <summary>
        /// EmailChangeLinkLiteral control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal EmailChangeLinkLiteral;

        /// <summary>
        /// AvatarImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image AvatarImage;

        /// <summary>
        /// UsernameTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox UsernameTextBox;

        /// <summary>
        /// EmailTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;

        /// <summary>
        /// RoleTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox RoleTextBox;

        /// <summary>
        /// AvatarUpload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload AvatarUpload;

        /// <summary>
        /// BioTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox BioTextBox;

        /// <summary>
        /// InterestsCheckBoxList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBoxList InterestsCheckBoxList;

        /// <summary>
        /// CurrentPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox CurrentPassword;

        /// <summary>
        /// NewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox NewPassword;

        /// <summary>
        /// ConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox ConfirmPassword;

        /// <summary>
        /// NewEmailTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox NewEmailTextBox;

        /// <summary>
        /// EmailCurrentPasswordTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EmailCurrentPasswordTextBox;

        /// <summary>
        /// SaveProfileButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button SaveProfileButton;

        /// <summary>
        /// RequestEmailChangeButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button RequestEmailChangeButton;
    }
}
